// @excalidraw/excalidraw resolves its lazily-loaded canvas fonts (as opposed
// to its own UI font, which ships as a normal @font-face) against
// `window.EXCALIDRAW_ASSET_PATH` as a *string URL prefix* — there is no
// data-URI "asset map" input in the 0.18.x API. The widget build works
// around that by pre-registering every font family via the FontFace API
// before Excalidraw mounts, using base64-embedded woff2 bytes baked into
// this generated module at build time (see vite.widget.config.ts).

export interface WidgetFontAsset {
  family: string
  // Path relative to @excalidraw/excalidraw's dist/prod/fonts directory —
  // doubles as the lookup key for the runtime fetch-shim fallback (matched
  // by basename against whatever URL Excalidraw's lazy loader requests).
  file: string
  weight?: string
  style?: string
  unicodeRange?: string
}

export interface ResolvedWidgetFont extends WidgetFontAsset {
  dataUri: string
}

export function resolveWidgetFontAssets(
  assets: readonly WidgetFontAsset[],
  readFile: (file: string) => Uint8Array,
): ResolvedWidgetFont[] {
  return assets.map((asset) => {
    const bytes = readFile(asset.file)
    const base64 = Buffer.from(bytes).toString('base64')
    return {
      ...asset,
      dataUri: `data:font/woff2;base64,${base64}`,
    }
  })
}

function basename(path: string): string {
  const parts = path.split('/')
  return parts[parts.length - 1] ?? path
}

// Generates plain JS (not TS) source: it is loaded as a Vite virtual module,
// never type-checked, so there's no benefit to TS syntax here and every byte
// saved matters once the fonts are inlined at multi-hundred-KB base64 sizes.
export function buildWidgetFontsModuleSource(fonts: readonly ResolvedWidgetFont[]): string {
  const fontEntries = fonts.map((font) => {
    const descriptorLines = [`"family": ${JSON.stringify(font.family)}`]
    if (font.weight) descriptorLines.push(`"weight": ${JSON.stringify(font.weight)}`)
    if (font.style) descriptorLines.push(`"style": ${JSON.stringify(font.style)}`)
    if (font.unicodeRange) {
      descriptorLines.push(`"unicodeRange": ${JSON.stringify(font.unicodeRange)}`)
    }
    descriptorLines.push(`"dataUri": ${JSON.stringify(font.dataUri)}`)
    return `  { ${descriptorLines.join(', ')} }`
  })

  const filenameEntries = fonts.map(
    (font) => `  ${JSON.stringify(basename(font.file))}: ${JSON.stringify(font.dataUri)}`,
  )

  return [
    '// Generated by scripts/build-widget-fonts.mjs — do not edit by hand.',
    `export const WIDGET_FONTS = [\n${fontEntries.join(',\n')}\n]`,
    `export const FONT_FILENAME_MAP = {\n${filenameEntries.join(',\n')}\n}`,
    '',
  ].join('\n\n')
}
