// The widget pre-registers every font family via the FontFace API before
// the viewer mounts, using base64-embedded bytes baked into this generated
// module at build time (see vite.widget.config.ts) — the single-file widget
// build must stay self-contained with zero runtime font fetches.

export interface WidgetFontAsset {
  family: string
  // Path relative to this package's assets/fonts/ directory.
  file: string
  weight?: string
  style?: string
  unicodeRange?: string
}

export interface ResolvedWidgetFont extends WidgetFontAsset {
  dataUri: string
}

const FONT_MIME_TYPES: Readonly<Record<string, string>> = {
  woff2: 'font/woff2',
  woff: 'font/woff',
  ttf: 'font/ttf',
  otf: 'font/otf',
}

/** Derives the font MIME type from the asset's file extension; defaults to woff2. */
function mimeTypeFor(file: string): string {
  const extension = file.split('.').pop()?.toLowerCase()
  return (extension && FONT_MIME_TYPES[extension]) || 'font/woff2'
}

export function resolveWidgetFontAssets(
  assets: readonly WidgetFontAsset[],
  readFile: (file: string) => Uint8Array,
): ResolvedWidgetFont[] {
  return assets.map((asset) => {
    const bytes = readFile(asset.file)
    const base64 = Buffer.from(bytes).toString('base64')
    return {
      ...asset,
      dataUri: `data:${mimeTypeFor(asset.file)};base64,${base64}`,
    }
  })
}

// Generates plain JS (not TS) source: it is loaded as a Vite virtual module,
// never type-checked, so there's no benefit to TS syntax here and every byte
// saved matters once the fonts are inlined at multi-hundred-KB base64 sizes.
export function buildWidgetFontsModuleSource(fonts: readonly ResolvedWidgetFont[]): string {
  const fontEntries = fonts.map((font) => {
    const descriptorLines = [`"family": ${JSON.stringify(font.family)}`]
    if (font.weight) descriptorLines.push(`"weight": ${JSON.stringify(font.weight)}`)
    if (font.style) descriptorLines.push(`"style": ${JSON.stringify(font.style)}`)
    if (font.unicodeRange) {
      descriptorLines.push(`"unicodeRange": ${JSON.stringify(font.unicodeRange)}`)
    }
    descriptorLines.push(`"dataUri": ${JSON.stringify(font.dataUri)}`)
    return `  { ${descriptorLines.join(', ')} }`
  })

  return [
    '// Generated by vite.widget.config.ts — do not edit by hand.',
    `export const WIDGET_FONTS = [\n${fontEntries.join(',\n')}\n]`,
    '',
  ].join('\n\n')
}
