language: node_js
node_js:
  - "8"
  - "10"
  - "11"
  - node
# safelist
branches:
  only:
  - master

before_install:
  # yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

script:
  - yarn lint
  - yarn build
  - yarn test

dist: trusty
cache:
  yarn: true
  directories:
    - node_modules
